server:
  port: 0
  error:
    whitelabel:
      enabled: false
  servlet:
    # TODO : CONTEXT-PATH가 해당 서비스명과 같은지 확인
    context-path: /api/festival-service
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

spring:
  application:
    name: festival-service

  zipkin:
    # TODO : 서버에 Open Zipkin Jar 파일 다운로드 후 실행하면 연결됨
    base-url: ""
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: ""
    port: 5672
    username: guest
    password: guest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ""
      #defaultZone: http://localhost:8761/eureka

cloud:
  aws:
    s3:
      bucket: jeonwoochi
    credentials:
      access-key: ""
      secret-key: ""
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
api:
  kakaoKey : ""

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, busrefresh

